spring.application.name=Coinkeeper
spring.profiles.active=test

springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.show-actuador=true

jwt.secret=StringUsadaParaGerarToken
jwt.expirada=180000

